# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34bd6099f19d5f246f58df1b24dc38166fa9fe9ec66eb5f253e8287c6e97950537e7f8d8c6177a43d564f767e4d85a09715ee5eabd3ef7871e8f26abcf7b4d5f

test:
  secret_key_base: dcbdae193151494afc84923e456a1cee8fa0ac3345f3beef4fc4e2b46bfb4a258ada2bdcb8adaec709649b5d61386c8f4d760ca073ae7725c670c12e71d19dfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
